substitutions:
  name: "apollo-m-1"
  friendly_name: "Apollo M-1"

  # ===== Display / Panel =====
  PANEL_W: "64"
  PANEL_H: "64"
  DISPLAY_CHAIN_LEN: "2" # Total number of panels you have connected
  DISPLAY_W: "128" # Most likely ${PANEL_W} * ${DISPLAY_CHAIN_LEN}
  DISPLAY_H: "64"  # Most likely ${PANEL_H}

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: stuartparmenter.apollo-m1-playground
    version: "0.3"

logger:

api:

ota:
  platform: esphome

wifi:
  ap:

captive_portal:

dashboard_import:
  package_import_url: github://stuartparmenter/apollo-m1-playground/project-template-rev7.yaml@test
  import_full_config: true

packages:
  # Base board/pins, LVGL root, services, etc.
  - !include packages/apollo-m1-rev7.yaml

  # Shared fonts and LVGL styles
  - !include styles.yaml

  # Pages (comment out to disable)
  - !include packages/page-bios.yaml

  # Page that uses lvgl-canvas-fx to render various effects (and change which in HA)
  - !include packages/page-fx.yaml

  # Microphone EQ Visualization
  # - !include packages/page-eq.yaml

  # A classic
  - !include packages/page-pong.yaml

#
# Below is included only in the factory firmware to make provisioning easier
#
esp32_improv:
  authorizer: none

improv_serial:
