substitutions:
  # ===== Display / Panel (shared) =====
  DISPLAY_W: "64"
  DISPLAY_H: "64"
  DISPLAY_CHAIN_LEN: "1"

  # ===== Weather page (page-weather-*) =====
  WX_ENTITY: "weather.home"
  HIGH_ENTITY: "sensor.weather_today_high"
  LOW_ENTITY:  "sensor.weather_today_low"
  UNITS: "°"

  # ===== Presence / Security (page-clock, etc.) =====
  ALARM_ENTITY: "alarm_control_panel.example_alarm"
  PERSON_A: "person.person_a"
  PERSON_B: "person.person_b"
  # account-circle / account-circle-outline, change to whatever you like
  PERSON_A_ICON: "\U000F040A"
  PERSON_B_ICON: "\U000F0B8F"

  # ===== DDP/WS Stream (page-ddp-stream) =====
  WS_DDP_HOST: "192.168.1.200"
  WS_DDP_PORT: "8788"
  DDP_PORT: "4048"
  DEFAULT_VIDEO_SRC: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" # or "mario.gif" or https://... / file:///sd/... etc.

  # ===== MSR-2 Radar Screen =====
  MSR2_PREFIX: apollo_msr_2_xxxxxx
