# © Copyright 2025 Stuart Parmenter
# SPDX-License-Identifier: MIT

# Helpers/sensors/etc
time:
  - platform: homeassistant
    id: ha_time

external_components:
  - source: github://stuartparmenter/lvgl-page-manager@main
    components: [lvgl_page_manager]

lvgl_page_manager:
  sort: by_order
  select:
    name: "Select Page"
    icon: "mdi:book-open-page-variant"
  next_button:
    name: "Page Next"
    icon: "mdi:page-next"
  prev_button:
    name: "Page Previous"
    icon: "mdi:page-previous"

# Home Assistant–exposed buttons that call those scripts
button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
    entity_category: "diagnostic"

# Matrix display controls
switch:
  - platform: template
    name: "Power"
    id: power
    icon: "mdi:power"
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    turn_on_action:
      - lambda: |-
          id(matrix).set_brightness((uint8_t)id(brightness).state);
    turn_off_action:
      - lambda: |-
          id(matrix).set_brightness(0);

number:
  - platform: template
    name: "Brightness"
    id: brightness
    icon: "mdi:brightness-6"
    min_value: 1
    max_value: 255
    step: 1
    optimistic: true
    restore_value: true
    initial_value: 128
    on_value:
      then:
        - lambda: |-
            if (id(power).state) {
              id(matrix).set_brightness((uint8_t)x);
            }

# Memory reporting sensor
sensor:
  - platform: template
    name: "Free Heap (Internal)"
    device_class: data_size
    state_class: measurement
    entity_category: diagnostic
    unit_of_measurement: "B"
    update_interval: 5s
    lambda: |-
      #include "esp_heap_caps.h"
      // Bytes of free internal heap
      return (float) heap_caps_get_free_size(MALLOC_CAP_8BIT | MALLOC_CAP_DMA | MALLOC_CAP_INTERNAL);
    disabled_by_default: true

  - platform: template
    name: "Free Heap (PSRAM)"
    device_class: data_size
    state_class: measurement
    entity_category: diagnostic
    unit_of_measurement: "KiB"
    update_interval: 5s
    lambda: |-
      #include "esp_heap_caps.h"
      // KBytes of free psram heap
      return (float) heap_caps_get_free_size(MALLOC_CAP_SPIRAM) / 1024;
    disabled_by_default: true

  - platform: internal_temperature
    name: "ESP Temperature"
    id: sys_esp_temperature
    entity_category: "diagnostic"
    disabled_by_default: true

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s
    entity_category: "diagnostic"
    disabled_by_default: true

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    disabled_by_default: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
      icon: "mdi:ip-outline"
      entity_category: "diagnostic"
      disabled_by_default: true