# © Copyright 2025 Stuart Parmenter
# SPDX-License-Identifier: MIT

substitutions:
  PANEL_W: "64"
  PANEL_H: "64"

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    advanced:
      compiler_optimization: PERF
      enable_idf_experimental_features: true
    sdkconfig_options:
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y

external_components:
  - source: github://stuartparmenter/ESPHome-HUB75-MatrixDisplayWrapper@main

display:
  - platform: hub75_matrix_display
    id: matrix
    width: ${PANEL_W}
    height: ${PANEL_H}
    chain_length: ${DISPLAY_CHAIN_LEN}
    clock_phase: false # fixes off by 1 issue
    latch_blanking: 1
    i2sspeed: HZ_20M

    # Apollo Automation M-1 Controller specific pin mappings
    # Rev4
    R1_pin: 42
    G1_pin: 41
    B1_pin: 40
    R2_pin: 38
    G2_pin: 39
    B2_pin: 37
    A_pin:
      number: 45
      ignore_strapping_warning: true
    B_pin: 36
    C_pin: 48
    D_pin: 35
    E_pin: 21
    LAT_pin: 47
    OE_pin: 14
    CLK_pin: 2

    # for LVGL
    double_buffer: false
    auto_clear_enabled: false
    update_interval: never

lvgl:
  buffer_size: 100%
  displays:
    - matrix
