# © Copyright 2025 Stuart Parmenter
# SPDX-License-Identifier: MIT

substitutions:
  PANEL_W: "64"
  PANEL_H: "64"

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    advanced:
      compiler_optimization: PERF
      enable_idf_experimental_features: true
    sdkconfig_options:
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y

external_components:
  - source: github://stuartparmenter/hub75-esphome@main

display:
  - platform: hub75
    id: matrix
    board: apollo-automation-m1-rev4

    panel_width: ${panel_width}
    panel_height: ${panel_height}
    layout: ${layout}
    layout_rows: ${layout_rows}
    layout_cols: ${layout_cols}
    scan_wiring: ${scan_wiring}

    clock_phase: false
    latch_blanking: 1
    clock_speed: 20MHz

    bit_depth: 8

    # for LVGL
    double_buffer: false
    auto_clear_enabled: false
    update_interval: never

lvgl:
  buffer_size: 100%
  displays:
    - matrix
