# © Copyright 2025 Stuart Parmenter
# SPDX-License-Identifier: MIT

# =========================================
# DDP Stream Page (LVGL, ESP-IDF only)
# Tested with ESPHome 2025.8
# =========================================

substitutions:
  CANVAS_WIDTH: "64"
  CANVAS_HEIGHT: "64"
  OUT_ID: "1"

external_components:
  - source: github://stuartparmenter/lvgl-ddp-stream@dev
    components: [ddp_stream]

# UDP DDP sink + canvas bindings (no w/h required here)
ddp_stream:
  id: ddp
  port: ${DDP_PORT}
  present_on_timeout: true
  timeout_coverage: 0.90
  timeout_factor: 1.20
  default_fps: 25.0
  adapt_fps: true
  streams:
    - id: ${OUT_ID}
      canvas_id: "canvas64"
    # - id: 2
    #   canvas_id: "canvas32"


# -----------------------------
# LVGL page with a single canvas
# -----------------------------
lvgl:
  pages:
    - id: ddp_video
      widgets:
        - canvas:
            id: canvas64
            width: ${CANVAS_WIDTH}
            height: ${CANVAS_HEIGHT}

