name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 6'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        #### Modify below here to match your project ####
        file:
          - apollo-automation-m1-rev4
          - apollo-automation-m1-rev6
          - adafruit-matrix-portal-s3
        #### Modify above here to match your project ####

        esphome-version:
          - stable
          - beta
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: ESPHome ${{ matrix.esphome-version }}
        uses: esphome/build-action@ae5408cdbc4f70692bf8e345c4982bca05a93667 # v8.1.0
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}
      - name: ESPHome ${{ matrix.esphome-version }} Factory
        uses: esphome/build-action@ae5408cdbc4f70692bf8e345c4982bca05a93667 # v8.1.0
        with:
          yaml-file: ${{ matrix.file }}.factory.yaml
          version: ${{ matrix.esphome-version }}
